import { Router, Request } from "express";
import { z } from "zod";
import { discoveryService } from "./discovery.service";
import { matchingService } from "../matching/matching.service";
import { discoverQuerySchema } from "./discovery.validators";
import { validateQuery } from "../../middleware/validate";
import { authenticate } from "../../middleware/authenticate";
import { asyncHandler } from "../../utils/asyncHandler";

export const discoveryRouter = Router();

discoveryRouter.get(
  "/",
  authenticate,
  validateQuery(discoverQuerySchema),
  asyncHandler(async (req: Request & { validatedQuery?: z.infer<typeof discoverQuerySchema> }, res) => {
    const q = req.validatedQuery!;
    const { results, hasMore } = await discoveryService.getFeed(
      req.user!.id,
      {
        minAge: q.minAge,
        maxAge: q.maxAge,
        maxDistanceKm: q.maxDistanceKm,
        schoolId: q.schoolId,
        majorId: q.majorId,
        relationshipGoal: q.relationshipGoal,
        interestIds: q.interestIds,
        verifiedOnly: q.verifiedOnly,
        minCompatibility: q.minCompatibility,
      },
      { limit: q.limit, offset: q.offset },
    );
    res.json({ results, hasMore, nextOffset: q.offset + results.length });
  }),
);

/** Compatibility breakdown between the viewer and a specific candidate (profile detail view). */
discoveryRouter.get(
  "/compatibility/:userId",
  authenticate,
  asyncHandler(async (req, res) => {
    const result = await matchingService.scorePair(req.user!.id, req.params.userId);
    res.json({
      ...result,
      note: "This compatibility score is an estimate generated by Campus Pulse based on your profiles — not a guarantee.",
    });
  }),
);
