import { discoveryRepository, DiscoverFilters } from "./discovery.repository";
import { matchingRepository } from "../matching/matching.repository";
import { matchingConfigService } from "../matching/matching.config";
import { computeCompatibility, haversineDistanceKm } from "../matching/matching.algorithm";
import { pool } from "../../db/pool";
import { AppError } from "../../middleware/errorHandler";

function calculateAge(dateOfBirth: string): number {
  const dob = new Date(dateOfBirth);
  const diff = Date.now() - dob.getTime();
  return Math.floor(diff / (1000 * 60 * 60 * 24 * 365.25));
}

export interface DiscoverResultItem {
  userId: string;
  firstName: string;
  age: number;
  bio: string;
  verified: boolean;
  photoUrl: string | null;
  relationshipGoal: string | null;
  distanceKm: number | null;
  compatibility: {
    score: number;
    factors: string[];
    note: string;
  };
}

export const discoveryService = {
  async getFeed(
    viewerId: string,
    filters: Omit<DiscoverFilters, "limit" | "offset"> & { minCompatibility?: number },
    page: { limit: number; offset: number },
  ): Promise<{ results: DiscoverResultItem[]; hasMore: boolean }> {
    const { rows: viewerProfileRows } = await pool.query<{
      max_distance_km: number;
      min_age_preference: number;
      max_age_preference: number;
    }>(`SELECT max_distance_km, min_age_preference, max_age_preference FROM profiles WHERE user_id = $1`, [
      viewerId,
    ]);
    const viewerProfile = viewerProfileRows[0];
    if (!viewerProfile) {
      throw new AppError(
        409,
        "ONBOARDING_INCOMPLETE",
        "Finish setting up your profile before browsing Discover.",
      );
    }

    const effectiveFilters: DiscoverFilters = {
      minAge: filters.minAge ?? viewerProfile.min_age_preference,
      maxAge: filters.maxAge ?? viewerProfile.max_age_preference,
      maxDistanceKm: filters.maxDistanceKm ?? viewerProfile.max_distance_km,
      schoolId: filters.schoolId,
      majorId: filters.majorId,
      relationshipGoal: filters.relationshipGoal,
      interestIds: filters.interestIds,
      verifiedOnly: filters.verifiedOnly,
      // Overfetch: some candidates get filtered out by precise distance / min
      // compatibility below, so we ask for more than the page size and trim after.
      limit: page.limit * 3 + 10,
      offset: page.offset,
    };

    const candidates = await discoveryRepository.findCandidates(viewerId, effectiveFilters);
    if (candidates.length === 0) return { results: [], hasMore: false };

    const [viewerCandidate, othersMap, weights] = await Promise.all([
      matchingRepository.getCandidate(viewerId),
      matchingRepository.getCandidates(candidates.map((c) => c.user_id)),
      matchingConfigService.getWeights(),
    ]);

    if (!viewerCandidate) {
      throw new AppError(409, "ONBOARDING_INCOMPLETE", "Finish setting up your profile before browsing Discover.");
    }

    const scored: DiscoverResultItem[] = [];

    for (const row of candidates) {
      const other = othersMap.get(row.user_id);
      if (!other) continue;

      let distanceKm: number | null = null;
      if (viewerCandidate.latitude != null && viewerCandidate.longitude != null && row.latitude != null && row.longitude != null) {
        distanceKm = haversineDistanceKm(viewerCandidate.latitude, viewerCandidate.longitude, row.latitude, row.longitude);
        const maxAcceptable = Math.min(viewerCandidate.maxDistanceKm, effectiveFilters.maxDistanceKm ?? Infinity);
        if (distanceKm > maxAcceptable) continue; // precise distance filter
      }

      const compatibility = computeCompatibility(viewerCandidate, other, weights);

      if (filters.minCompatibility != null && compatibility.score < filters.minCompatibility) continue;

      scored.push({
        userId: row.user_id,
        firstName: row.first_name,
        age: calculateAge(row.date_of_birth),
        bio: row.bio,
        verified: row.verified,
        photoUrl: row.photo_url,
        relationshipGoal: row.relationship_goal,
        distanceKm: distanceKm != null ? Math.round(distanceKm * 10) / 10 : null,
        compatibility: {
          score: compatibility.score,
          factors: compatibility.factors,
          note: "This compatibility score is an estimate generated by Campus Pulse based on your profiles — not a guarantee.",
        },
      });
    }

    scored.sort((a, b) => b.compatibility.score - a.compatibility.score);

    const pageResults = scored.slice(0, page.limit);
    return { results: pageResults, hasMore: scored.length > page.limit || candidates.length === effectiveFilters.limit };
  },
};
